---
title: "00_load_data"
author: "CS"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Load Packages
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table) #fread function
library(ggplot2)
```


2. Open Dataframes
```{r}
df_obsDeb <-fread('data/SACROIS_obsDeb_Sars_2018_2022_GSA07.csv', 
                 h=T, sep=';', dec='.', encoding="UTF-8")
df_effDeb <-fread('data/SACROIS_obsDeb_effort_Sars_2018_2022_GSA07.csv', 
                 h=T, sep=';', dec='.')
df_ANNEE_TEMP <-fread('data/ANNEE_TRIM_TEMPS.csv', 
                 h=T, sep=';', dec='.')
ports_long <-fread('data/ports_long.csv', 
                 h=T, sep=';', dec='.')

```


3. Observe data and clean
```{r}

unique(df_obsDeb[,3])

# Change encoding 
df_obsDeb[,2:13] <- as.data.frame ( apply(df_obsDeb[,2:13], 2, function(colonne){
  colonne <- iconv(colonne, from = "UTF-8", to = "LATIN1")
  return(colonne)}) )

df_effDeb[,2:13] <- as.data.frame ( apply(df_effDeb[,2:13], 2, function(colonne){
  colonne <- iconv(colonne, from = "UTF-8", to = "LATIN1")
  return(colonne)}) )

# change class
df_obsDeb$TRIMESTRE <- as.integer(df_obsDeb$TRIMESTRE)
df_effDeb$TRIMESTRE <- as.integer(df_effDeb$TRIMESTRE)
df_obsDeb$ANNEE <- as.integer(df_obsDeb$ANNEE)
df_effDeb$ANNEE <- as.integer(df_effDeb$ANNEE)
df_ANNEE_TEMP <- df_ANNEE_TEMP %>% group_by(ANNEE, TRIMESTRE, TEMPS)

# Order port from Est to Ouest
df_obsDeb$PORT_EXP_LIB = as.factor(df_obsDeb$PORT_EXP_LIB)
levels(df_obsDeb$PORT_EXP_LIB)


df_obsDeb$PORT_EXP_LIB <- factor(df_obsDeb$PORT_EXP_LIB, 
                                 levels = c(
  "Etang de Bages-Sigean, Peyriac de mer",
  "Etang de Salse-Leucate, Port Barcarès",
  "Canet-en-Roussillon",
  "Saint-Cyprien",
  "Port St Ange",
  "Etang de Bages-Sigean, Bages",
  "Port-la-Nouvelle",
  "Port-Leucate",
  "Etang de Salse-Leucate,Salse - la Rouquette",
  "Grau de Leucate",
  "Argelès-sur-Mer, Le Racou",
  "Etang de l'Ayrolle",
  "Gruissan",
  "Port-Vendres",
  "Banyuls-sur-Mer",
  "Narbonne Plage",
  "Hyères, St Pierre sur mer",
  "Les Cabanes de Fleury",
  "Valras-Plage",
  "Grau d'Agde",
  "Cap d'Agde",
  "Etang de Thau, Marseillan",
  "Marseillan-plage",
  "Etang de Thau, Pte Courte, Barrou, Zup",
  "Etang de Thau, Mèze, le Mourre Blanc",
  "Frontignan",
  "Etang de Thau, Bouzigues",
  "Etang de Thau, Balaruc",
  "Sète-Mole et canaux",
  "Etangs de Vic, Moures, Arnel, Prévost, P. Blanches",
  "Etang d'Ingril, Les Aresquiers",
  "Palavas-les-Flots",
  "Etang de Mauguio, Cabanes de Pérols,Mauguio",
  "Etang de Mauguio, Cabanes de Lunel",
  "Carnon-Plage",
  "Le-Grau-du-Roi",
  "Saintes-Maries-de-la-Mer, Port Cardian",
  "Darse de l'Amarrée et port Dromar",
  "Cabanes de Beauduc",
  "Les Salins de Giraud",
  "Port-Saint-Louis-du-Rhône",
  "Fos sur Mer, port St Gervais",
  "Port-de-Bouc, Anse Aubran",
  "Martigues",
  "Etang de Berre, Istres -les heures Claires",
  "Anse des laurons",
  "Carro",
  "Etang de Berre, Saint-Chamas",
  "Port de Carteau",
  "Sausset-les-Pins",
  "Etang de Berre, La Mède",
  "Etang de Berre, Port de Sagnas",
  "Carry-le-Rouet",
  "Etang de Berre, Port du Jaï (Marignane)",
  "La Redonne, Méjean",
  "Etang de Berre, Berre - Port de passet",
  "L'Estaque",
  "Saumaty",
  "Port des Goudes",
  "Vallon des Auffes",
  "La Madrague de Montredon",
  "Vieux Port de Marseille",
  "Port de Morgiou",
  "Cassis",
  "La Ciotat",
  "St Cyr sur mer, la Madrague",
  "Bandol",
  "Le Brusc (Six-Fours-les-Plages)",
  "Sanary-sur-Mer",
  "Port de la Coudoulière",
  "La Seyne-sur-Mer",
  "St Elme",
  "St Mandrier sur mer",
  "Toulon",
  "Port St Louis du Mourillon",
  "Port des Oursinières",
  "Carqueiranne, les salettes",
  "Giens, la Madrague",
  "Giens, Ports du Niel, de la Tour Fondue",
  "Port de l'Ayguade",
  "Port de Porquerolles (Ile de)",
  "Salins d'Hyères, Pothuau",
  "La Londe des Maures, Miramar",
  "Port de Bormes les Mimosas, La Favière",
  "Le Lavandou",
  "Cavalaire sur Mer",
  "Les Marines de Cogolin et Port Grimaud",
  "Saint-Tropez, vieux port",
  "Ste Maxime",
  "San Peire, la Garonnette",
  "Fréjus",
  "Saint-Raphaël, vieux port",
  "Drammont, la Poussai",
  "Agay",
  "La Figueirette",
  "Cannes, Nourée Rouge",
  "Théoule",
  "La Rague",
  "Mandelieu-La Napoule",
  "La Galère",
  "Cannes, vieux port",
  "Golfe Juan (Vallauris)",
  "Juan les Pins",
  "Port de Crouton",
  "Port Vauban",
  "Antibes, tous les ports",
  "Villeneuve Loubet",
  "Cros de Cagnes",
  "Nice",
  "Villefranche-sur-Mer, tous les ports",
  "Villefranche, Port de la Santé",
  "St Jean Cap Ferrat",
  "Baulieu",
  "Beaulieu-sur-mer",
  "Menton, vieux port, Garavan",
  "Sagone"
))

#Add TEMP variable
df_obsDeb <- left_join(df_obsDeb, df_ANNEE_TEMP)
df_effDeb <- left_join(df_effDeb, df_ANNEE_TEMP)

# observe data 
apply(df_obsDeb[,2:13], 2, unique)
apply(df_effDeb[,2:13], 2, unique)

```

Save dataframes
```{r}
save(df_obsDeb, file = "data/df_obsDeb.RData")
save(df_effDeb, file = "data/df_effDeb.RData")
save(df_ANNEE_TEMP, file = "data/df_ANNEE_TEMP.RData")

```



